### ISSUE TITLE
Question: [NestJS] How to use with global AppGuard?

### ISSUE THREAD

**Issue by dimbslmh** [femike/swagger-protect-ui#2]
I am using a global guard with a custom `@Public()` decorator as shown here: https://docs.nestjs.com/security/authentication#enable-authentication-globally

I have tried adding the loginPath like this:

```ts
app.setGlobalPrefix('api/v1', {
  exclude: ['login-api'],
})
```

But it's not getting passed the global guard. Please advice.

**Comment by femike** [comment]
Can you plz create example on stackblitz.com
You can fork this example
https://stackblitz.com/edit/nestjs-swagger-protect-express

**Comment by dimbslmh** [comment]
Thanks for responding @femike. I solved it by checking the url of the request inside the global guard.

```ts
const request = context.switchToHttp().getRequest();
const url: string = request.raw.url;
```

There is something else though that may be a bug (using inject with `SwaggerProtect.forRootAsync<'fastify'>`). 
I'll try to reproduce it first on stackblitz before I make a bug report. Thank you
